services:
  postgres:
    image: postgres
    container_name: bingodb
    ports:
      - 5433:5432
    networks:
      - bingonetwork
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - bingovolume:/var/lib/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d postgres -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: bingobackend
    container_name: backend
    build: .
    ports:
      - 5000:5000
    networks:
      - bingonetwork
    env_file:
      - .env
    depends_on:
      postgres:
          condition: service_healthy
networks:
    bingonetwork:
      name: bingonetwork

volumes:
    bingovolume:

        